#pragma once

namespace core { namespace events {

	enum Event
	{
		PLAYER_MOVE,
		PLAYER_BLOCKED,
		PLAYER_NOT_BLOCKED,
		PLAYER_TRIGGER_ON,
		PLAYER_TRIGGER_OFF,
		AUDIO_PLAY_EFFECT,
		AUDIO_STOP_EFFECT,
		AUDIO_PLAY_MUSIC,
		AUDIO_STOP_MUSIC
	};

} }